import { Player, Faction, FactionInfo } from "./types";

export const factions: Record<Faction, FactionInfo> = {
  "jedi-order": {
    id: "jedi-order",
    name: "Jedi Order",
    side: "light",
    path: "force",
    tiers: [
      { name: "Grand Master", minRating: 2700 },
      { name: "Jedi Master", minRating: 2400 },
      { name: "Jedi Knight", minRating: 2000 },
      { name: "Padawan", minRating: 1500 },
      { name: "Youngling", minRating: 0 },
    ],
  },
  "rebel-alliance": {
    id: "rebel-alliance",
    name: "Rebel Alliance",
    side: "light",
    path: "military",
    tiers: [
      { name: "General", minRating: 2700 },
      { name: "Commander", minRating: 2400 },
      { name: "Pathfinder", minRating: 2000 },
      { name: "Trooper", minRating: 1500 },
      { name: "Recruit", minRating: 0 },
    ],
  },
  "sith-order": {
    id: "sith-order",
    name: "Sith Order",
    side: "dark",
    path: "force",
    tiers: [
      { name: "Darth", minRating: 2700 },
      { name: "Sith Lord", minRating: 2400 },
      { name: "Sith Warrior", minRating: 2000 },
      { name: "Apprentice", minRating: 1500 },
      { name: "Acolyte", minRating: 0 },
    ],
  },
  "galactic-empire": {
    id: "galactic-empire",
    name: "Galactic Empire",
    side: "dark",
    path: "military",
    tiers: [
      { name: "Grand Admiral", minRating: 2700 },
      { name: "Grand Moff", minRating: 2400 },
      { name: "Commander", minRating: 2000 },
      { name: "Officer", minRating: 1500 },
      { name: "Cadet", minRating: 0 },
    ],
  },
};

export function getPlayerTier(player: Player, rank: number) {
  if (rank === 1) {
    return { name: "The Chosen One", isChosenOne: true };
  }
  const faction = factions[player.faction];
  const tier = faction.tiers.find((t) => player.midichlorianIndex >= t.minRating) ?? faction.tiers[faction.tiers.length - 1];
  return { name: tier.name, isChosenOne: false };
}

export function getFactionSide(faction: Faction) {
  return factions[faction].side;
}

export const players: Player[] = [
  {
    id: "1",
    name: 'Darren "Krayt Dragon" Tan',
    country: "SG",
    midichlorianIndex: 2847,
    wins: 142,
    losses: 18,
    draws: 3,
    streak: 12,
    peakRating: 2871,
    favoriteAspect: "Command",
    faction: "jedi-order",
    tournamentWins: 8,
    lastActive: "2026-05-26",
  },
  {
    id: "2",
    name: "Elena Vasquez",
    country: "ES",
    midichlorianIndex: 2793,
    wins: 131,
    losses: 22,
    draws: 5,
    streak: 7,
    peakRating: 2810,
    favoriteAspect: "Cunning",
    faction: "sith-order",
    tournamentWins: 6,
    lastActive: "2026-05-27",
  },
  {
    id: "3",
    name: "Jake Morrison",
    country: "US",
    midichlorianIndex: 2756,
    wins: 128,
    losses: 25,
    draws: 2,
    streak: -2,
    peakRating: 2790,
    favoriteAspect: "Aggression",
    faction: "galactic-empire",
    tournamentWins: 5,
    lastActive: "2026-05-25",
  },
  {
    id: "4",
    name: "Yuki Tanaka",
    country: "JP",
    midichlorianIndex: 2721,
    wins: 119,
    losses: 28,
    draws: 4,
    streak: 5,
    peakRating: 2745,
    favoriteAspect: "Villainy",
    faction: "sith-order",
    tournamentWins: 4,
    lastActive: "2026-05-27",
  },
  {
    id: "5",
    name: "Marcus Webb",
    country: "GB",
    midichlorianIndex: 2698,
    wins: 115,
    losses: 30,
    draws: 6,
    streak: 3,
    peakRating: 2720,
    favoriteAspect: "Heroism",
    faction: "rebel-alliance",
    tournamentWins: 4,
    lastActive: "2026-05-24",
  },
  {
    id: "6",
    name: "Anika Schröder",
    country: "DE",
    midichlorianIndex: 2654,
    wins: 108,
    losses: 33,
    draws: 3,
    streak: -1,
    peakRating: 2680,
    favoriteAspect: "Vigilance",
    faction: "jedi-order",
    tournamentWins: 3,
    lastActive: "2026-05-26",
  },
  {
    id: "7",
    name: "Lucas Ferreira",
    country: "BR",
    midichlorianIndex: 2631,
    wins: 104,
    losses: 35,
    draws: 2,
    streak: 8,
    peakRating: 2650,
    favoriteAspect: "Aggression",
    faction: "galactic-empire",
    tournamentWins: 3,
    lastActive: "2026-05-27",
  },
  {
    id: "8",
    name: "Sophie Chen",
    country: "CA",
    midichlorianIndex: 2609,
    wins: 101,
    losses: 37,
    draws: 5,
    streak: 1,
    peakRating: 2635,
    favoriteAspect: "Command",
    faction: "rebel-alliance",
    tournamentWins: 2,
    lastActive: "2026-05-23",
  },
  {
    id: "9",
    name: "Omar Al-Rashid",
    country: "AE",
    midichlorianIndex: 2587,
    wins: 97,
    losses: 39,
    draws: 4,
    streak: -3,
    peakRating: 2620,
    favoriteAspect: "Cunning",
    faction: "jedi-order",
    tournamentWins: 2,
    lastActive: "2026-05-26",
  },
  {
    id: "10",
    name: "Camille Dubois",
    country: "FR",
    midichlorianIndex: 2564,
    wins: 94,
    losses: 41,
    draws: 3,
    streak: 4,
    peakRating: 2590,
    favoriteAspect: "Villainy",
    faction: "sith-order",
    tournamentWins: 2,
    lastActive: "2026-05-25",
  },
  {
    id: "11",
    name: "Kim Seung-ho",
    country: "KR",
    midichlorianIndex: 2541,
    wins: 91,
    losses: 43,
    draws: 2,
    streak: 2,
    peakRating: 2565,
    favoriteAspect: "Heroism",
    faction: "rebel-alliance",
    tournamentWins: 1,
    lastActive: "2026-05-27",
  },
  {
    id: "12",
    name: "Matteo Rossi",
    country: "IT",
    midichlorianIndex: 2518,
    wins: 88,
    losses: 45,
    draws: 4,
    streak: -4,
    peakRating: 2560,
    favoriteAspect: "Vigilance",
    faction: "galactic-empire",
    tournamentWins: 1,
    lastActive: "2026-05-22",
  },
  {
    id: "13",
    name: "Nina Johansson",
    country: "SE",
    midichlorianIndex: 2495,
    wins: 85,
    losses: 47,
    draws: 3,
    streak: 6,
    peakRating: 2530,
    favoriteAspect: "Command",
    faction: "jedi-order",
    tournamentWins: 1,
    lastActive: "2026-05-26",
  },
  {
    id: "14",
    name: "Ryan O'Sullivan",
    country: "IE",
    midichlorianIndex: 2472,
    wins: 82,
    losses: 49,
    draws: 5,
    streak: 1,
    peakRating: 2510,
    favoriteAspect: "Aggression",
    faction: "galactic-empire",
    tournamentWins: 1,
    lastActive: "2026-05-24",
  },
  {
    id: "15",
    name: "Priya Sharma",
    country: "IN",
    midichlorianIndex: 2449,
    wins: 79,
    losses: 51,
    draws: 2,
    streak: -2,
    peakRating: 2485,
    favoriteAspect: "Cunning",
    faction: "sith-order",
    tournamentWins: 0,
    lastActive: "2026-05-25",
  },
  {
    id: "16",
    name: "Diego Morales",
    country: "MX",
    midichlorianIndex: 2426,
    wins: 76,
    losses: 53,
    draws: 4,
    streak: 3,
    peakRating: 2460,
    favoriteAspect: "Villainy",
    faction: "galactic-empire",
    tournamentWins: 0,
    lastActive: "2026-05-27",
  },
  {
    id: "17",
    name: "Zara Okafor",
    country: "NG",
    midichlorianIndex: 2403,
    wins: 73,
    losses: 55,
    draws: 3,
    streak: 5,
    peakRating: 2440,
    favoriteAspect: "Heroism",
    faction: "rebel-alliance",
    tournamentWins: 0,
    lastActive: "2026-05-26",
  },
  {
    id: "18",
    name: "Anton Petrov",
    country: "BG",
    midichlorianIndex: 2380,
    wins: 70,
    losses: 57,
    draws: 2,
    streak: -1,
    peakRating: 2415,
    favoriteAspect: "Vigilance",
    faction: "jedi-order",
    tournamentWins: 0,
    lastActive: "2026-05-23",
  },
  {
    id: "19",
    name: "Isla McTavish",
    country: "NZ",
    midichlorianIndex: 2357,
    wins: 67,
    losses: 59,
    draws: 4,
    streak: 2,
    peakRating: 2390,
    favoriteAspect: "Command",
    faction: "rebel-alliance",
    tournamentWins: 0,
    lastActive: "2026-05-25",
  },
  {
    id: "20",
    name: "Thomas Lindqvist",
    country: "FI",
    midichlorianIndex: 2334,
    wins: 64,
    losses: 61,
    draws: 3,
    streak: -5,
    peakRating: 2380,
    favoriteAspect: "Aggression",
    faction: "sith-order",
    tournamentWins: 0,
    lastActive: "2026-05-24",
  },
];

export function getWinRate(player: Player): number {
  const total = player.wins + player.losses + player.draws;
  if (total === 0) return 0;
  return Math.round((player.wins / total) * 1000) / 10;
}

export function getTotalGames(player: Player): number {
  return player.wins + player.losses + player.draws;
}

export const aspectColors: Record<string, string> = {
  Vigilance: "#3b82f6",
  Command: "#22c55e",
  Aggression: "#ef4444",
  Cunning: "#eab308",
  Villainy: "#a855f7",
  Heroism: "#06b6d4",
};
